package com.xiaomi.mi_connect_sdk.api;

public enum ResultCode {
    GENERAL_SUCCESS(0),
    START_DISCOVERY_SUCCESS(1),
    STOP_DISCOVERY_SUCCESS(2),
    START_ADVERTISING_SUCCESS(3),
    STOP_ADVERTISING_SUCCESS(4),
    REQUEST_CONNECTION_SUCCESS(5),
    ACCEPT_CONNECTION_SUCCESS(6),
    REJECT_CONNECTION_SUCCESS(7),
    DISCONNECT_FROM_END_POINT_SUCCESS(8),
    SEND_PAYLOAD_SUCCESS(9),
    DISCOVERY_END(10),
    GENERAL_ERROR(-1),
    APP_NOT_SUPPORT_ERROR(-2),
    SERVICE_ERROR(-3),
    ILLEGAL_ARGUMENT_ERROR(-4),
    ALREADY_ADVERTISING(-5),
    ALREADY_DISCOVERY(-6),
    START_ADVERTISING_ERROR(-7),
    STOP_ADVERTIDING_ERROR(-8),
    START_DISCOVERY_ERROR(-9),
    STOP_DISCOVERY_ERROR(-10),
    SEND_PAYLOAD_ERROR(-11),
    NOT_IN_ADVERTISING(-12),
    NOT_IN_DISCOVERY(-13),
    ENDPOINT_ID_INVALID(-14),
    LOCALAPP_ID_INVALID(-15),
    SERVICE_INCOMPATIBLE(-16),
    SERVER_OCCUPIED(-17),
    DISCOVERY_NOT_ALLOWED_IN_CONNECTION(-18),
    SERVER_NOT_EXITENT(-19),
    REJECTED(-20),
    COMMUNICATION_ERROR(-21),
    REMOTE_CLINET_NOT_EXITENT(-22),
    UNKNOWN_ERROR(-9999);
    
    private int code;

    private ResultCode(int i) {
        this.code = i;
    }

    public static ResultCode fromInt(int i) {
        return i == 0 ? GENERAL_SUCCESS : i == 1 ? START_DISCOVERY_SUCCESS : i == 2 ? STOP_DISCOVERY_SUCCESS : i == 3 ? START_ADVERTISING_SUCCESS : i == 4 ? STOP_ADVERTISING_SUCCESS : i == 5 ? REQUEST_CONNECTION_SUCCESS : i == 6 ? ACCEPT_CONNECTION_SUCCESS : i == 7 ? REJECT_CONNECTION_SUCCESS : i == 8 ? DISCONNECT_FROM_END_POINT_SUCCESS : i == 9 ? SEND_PAYLOAD_SUCCESS : i == 10 ? DISCOVERY_END : i == -1 ? GENERAL_ERROR : i == -2 ? APP_NOT_SUPPORT_ERROR : i == -3 ? SERVICE_ERROR : i == -4 ? ILLEGAL_ARGUMENT_ERROR : i == -5 ? ALREADY_ADVERTISING : i == -6 ? ALREADY_DISCOVERY : i == -7 ? START_ADVERTISING_ERROR : i == -8 ? STOP_ADVERTIDING_ERROR : i == -9 ? START_DISCOVERY_ERROR : i == -10 ? STOP_DISCOVERY_ERROR : i == -11 ? SEND_PAYLOAD_ERROR : i == -12 ? NOT_IN_ADVERTISING : i == -13 ? NOT_IN_DISCOVERY : i == -14 ? ENDPOINT_ID_INVALID : i == -15 ? LOCALAPP_ID_INVALID : i == -16 ? SERVICE_INCOMPATIBLE : i == -17 ? SERVER_OCCUPIED : i == -18 ? DISCOVERY_NOT_ALLOWED_IN_CONNECTION : i == -19 ? SERVER_NOT_EXITENT : i == -20 ? REJECTED : i == -21 ? COMMUNICATION_ERROR : i == -22 ? REMOTE_CLINET_NOT_EXITENT : UNKNOWN_ERROR;
    }

    public int getCode() {
        return this.code;
    }
}
